IHE/ITI.mCSD

input/images-source/ITI-90-seq.plantuml
input/pagecontent/ITI-90.md
input/pagecontent/issues.md

Added in section for a retrieve resource message and updated issues to refer to the addition.  
Also added sentence to say search can use GET or POST.

Add GET/POST and Retrieve resource message.

---

input/fsh/healthcareservice.fsh
input/fsh/jurisdiction.fsh

Fixed whitespace warnings.

---

input/pagecontent/volume-1.md

Updated text to link to mCSD Whitepaper and add link to SVCM to fix #36 and #74 .

Minor updates for Issues 36 and 74

---

input/pagecontent/volume-1.md

Update volume-1.md - typo

---

input/fsh/codes.fsh
input/fsh/facility.fsh
input/fsh/jurisdiction.fsh
input/fsh/org-aff.fsh
input/fsh/rules.fsh
input/pagecontent/issues.md

Use codesystem and slice for Facility/Jurisdiction.  Fixes #80 
Use slice for organization affliation.  Fixes #32

Changed to use slices instead of invariant

---

input/fsh/org-aff.fsh

Removed must support from specialty and location on OrganizationAffiliation.
Fixes #69

Organization Affiliation must support

---

input/fsh/endpoint.fsh
input/fsh/healthcareservice.fsh
input/fsh/location.fsh
input/fsh/org-aff.fsh
input/fsh/organization.fsh
input/fsh/practitioner.fsh

Fixes #67 to remove implicitRules and modifierExtension from the profiled resources.

implicitRules and modifierExtension

---

input/fsh/endpoint.fsh
input/fsh/organization.fsh
input/fsh/purpose.fsh

Fixes #59 to add in purpose of use extension and search parameter.

Added in purpose of use extension for organization and endpoint.

---

input/fsh/endpoint.fsh
input/fsh/purpose.fsh
input/pagecontent/ITI-90.md
input/resources/capabilitystatement-IHE.mCSD.CareServicesSelectiveConsumer.xml
input/resources/capabilitystatement-IHE.mCSD.CareServicesSelectiveSupplier.xml

Updated capability statements and ITI-90 to simplify the required search parameters.

Streamlined search parameters.  Fixes #51.

---

input/fsh/Aliases.fsh
input/fsh/audit-90.fsh
input/fsh/audit-91.fsh
input/fsh/ex-audit-90.fsh
input/fsh/ex-audit91.fsh
input/pagecontent/ITI-90.md
input/pagecontent/ITI-91.md
sushi-config.yaml

Added in audit events with examples and linked from the security considerations sections.

Added in audit events

---

input/fsh/endpoint.fsh

Closes #139
Added context to the Endpoint specific type extension

Added context to endpoint specific type extension.

---

input/pagecontent/ITI-90.md

Remove a space that prevented converting the markdown code to a link.

Fix markdown in ITI-90.md

---

input/fsh/audit-91.fsh
input/fsh/rules.fsh

Closes #159 
Changes the slice type to be value instead of pattern since pattern has been deprecated.

Changed slicing type to use value instead of pattern.  Fixes #159.

---

input/pagecontent/issues.md
publication-request.json
sushi-config.yaml

Prep for 3.9 release with CP-ITI-1290 integrated

Prep for mCSD 3.9 TI release

---

input/pagecontent/ITI-91.md
narrative-source/mCSD.md

This PR resolves an invalid link to the http history documentation of FHIR R4

Fix invalid URL to http://hl7.org/fhir/R4/http.html#history

---

input/pagecontent/ITI-130.md
input/pagecontent/index.md
input/pagecontent/issues.md
input/pagecontent/other.md
input/pagecontent/volume-1.md
sushi-config.yaml

Closes # 
Prepublication edits for Revision 4.0.0-comment

Prepublication edits for Rev. 4.0.0-comment

---

input/pagecontent/ITI-130.md

Typo fix from public comment review.
Closes #192 
Typo fixes for public comment review.  Will review during face to face.

Removed sentences that were a copy/paste error.  Fixes 192.

---

input/fsh/Aliases.fsh
input/fsh/org-aff.fsh
input/fsh/rules.fsh
input/pagecontent/index.md
input/pagecontent/issues.md
input/pagecontent/volume-1.md
sushi-config.yaml

Closes #95, #96, #99, #100,  #108, #132
This PR simplifies section 1:46.8 to reference and better align with the topologies white paper. 
It also replaces the mCSD Organization Affiliation Types code system with the HL7 Organization Affiliation Role for HIE code system. 
- [ X] My pull request adheres to the code style of this project

Whitepaper-cleanup

---

input/fsh/org-aff.fsh
input/images-source/ITI-130-seq.plantuml
input/images-source/ITI-90-seq.plantuml
input/images-source/ITI-91-seq.plantuml
input/images-source/basic-deployment.plantuml
input/images-source/dir-endpoint-to-hybrid-org-structure.plantuml
input/images-source/dir-endpoint-to-org-affiliates.plantuml
input/images-source/dir-endpoint-to-org-hierarchy.plantuml
input/images-source/dir-endpoint-xdr-mhd.plantuml
input/images-source/dir-org-specific-endpoint-affil.plantuml
input/images-source/dir-org-specific-endpoint-inter.plantuml
input/images-source/dir-org-specific-endpoint-parent.plantuml
input/images-source/dir-org-specific-endpoint-self.plantuml
input/images-source/simple-deployment.plantuml
input/images-source/usecase1-processflow.plantuml
input/images-source/usecase2-processflow.plantuml
input/images-source/usecase3-diagram.plantuml
input/images-source/usecase3-processflow.plantuml
input/images-source/usecase4-processflow.plantuml
input/images-source/usecase5-diagram.plantuml
input/images-source/usecase5-processflow.plantuml
input/images-source/usecase6-diagram.plantuml
input/images-source/usecase6-processflow.plantuml
input/images-source/usecase7-processflow.plantuml
input/pagecontent/ITI-130.md
input/pagecontent/ITI-90.md
input/pagecontent/ITI-91.md
input/pagecontent/volume-1.md

Closes # 
Editorial suggestions for version 4.0.0
- [ X] My pull request adheres to the code style of this project

Small editorial suggestions

---

input/pagecontent/ITI-130.md
input/pagecontent/ITI-90.md
input/pagecontent/issues.md
input/pagecontent/volume-1.md

Prepublication edits for ITI.mCSD Rev. 4.0.0 for TI
